-- FocusFlow Supabase migration: user scoping + RLS
-- Run this in Supabase SQL Editor (or `supabase db push`) once.

begin;

-- 0) Create app tables if this is a fresh Supabase project
create table if not exists public.tasks (
  id integer generated by default as identity primary key,
  user_id uuid,
  title text not null,
  completed boolean not null default false,
  is_priority boolean not null default false,
  date date not null
);

create table if not exists public.habits (
  id integer generated by default as identity primary key,
  user_id uuid,
  name text not null
);

create table if not exists public.habit_logs (
  id integer generated by default as identity primary key,
  user_id uuid,
  habit_id integer not null,
  date date not null,
  completed boolean not null default false
);

create table if not exists public.study_sessions (
  id integer generated by default as identity primary key,
  user_id uuid,
  subject text not null,
  topic text not null,
  duration_minutes integer not null,
  date date not null
);

create table if not exists public.daily_reflections (
  id integer generated by default as identity primary key,
  user_id uuid,
  date date not null,
  content text not null
);

create table if not exists public.weekly_reviews (
  id integer generated by default as identity primary key,
  user_id uuid,
  week_start_date date not null,
  total_study_hours integer not null,
  topics_completed text not null,
  weak_subjects text not null,
  wins text not null,
  improvements text not null,
  next_week_plan text not null
);

create table if not exists public.monthly_reviews (
  id integer generated by default as identity primary key,
  user_id uuid,
  month text not null,
  total_study_hours integer not null,
  subject_summary text not null,
  habit_consistency integer not null,
  insight text not null,
  next_month_focus text not null
);

-- 1) Ensure user_id exists and is UUID on all app tables
alter table if exists public.tasks add column if not exists user_id uuid;
alter table if exists public.habits add column if not exists user_id uuid;
alter table if exists public.habit_logs add column if not exists user_id uuid;
alter table if exists public.study_sessions add column if not exists user_id uuid;
alter table if exists public.daily_reflections add column if not exists user_id uuid;
alter table if exists public.weekly_reviews add column if not exists user_id uuid;
alter table if exists public.monthly_reviews add column if not exists user_id uuid;

-- If a previous migration stored user_id as text, convert to uuid
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tasks' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.tasks
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'habits' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.habits
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'habit_logs' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.habit_logs
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'study_sessions' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.study_sessions
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'daily_reflections' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.daily_reflections
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'weekly_reviews' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.weekly_reviews
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'monthly_reviews' AND column_name = 'user_id'
      AND data_type IN ('text', 'character varying')
  ) THEN
    ALTER TABLE public.monthly_reviews
      ALTER COLUMN user_id TYPE uuid USING NULLIF(user_id::text, '')::uuid;
  END IF;
END $$;

-- 2) Clean old constraints that were global (not user-scoped)
alter table if exists public.daily_reflections drop constraint if exists daily_reflections_date_key;
alter table if exists public.weekly_reviews drop constraint if exists weekly_reviews_week_start_date_key;
alter table if exists public.monthly_reviews drop constraint if exists monthly_reviews_month_key;

-- 3) Remove rows without a user (safe for fresh/local datasets)
delete from public.habit_logs where user_id is null;
delete from public.daily_reflections where user_id is null;
delete from public.weekly_reviews where user_id is null;
delete from public.monthly_reviews where user_id is null;
delete from public.study_sessions where user_id is null;
delete from public.tasks where user_id is null;
delete from public.habits where user_id is null;

-- 4) Enforce NOT NULL user ownership
alter table if exists public.tasks alter column user_id set not null;
alter table if exists public.habits alter column user_id set not null;
alter table if exists public.habit_logs alter column user_id set not null;
alter table if exists public.study_sessions alter column user_id set not null;
alter table if exists public.daily_reflections alter column user_id set not null;
alter table if exists public.weekly_reviews alter column user_id set not null;
alter table if exists public.monthly_reviews alter column user_id set not null;

-- 5) Add FK to Supabase auth.users
alter table if exists public.tasks
  drop constraint if exists tasks_user_id_fkey,
  add constraint tasks_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

alter table if exists public.habits
  drop constraint if exists habits_user_id_fkey,
  add constraint habits_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

alter table if exists public.habit_logs
  drop constraint if exists habit_logs_user_id_fkey,
  add constraint habit_logs_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

alter table if exists public.study_sessions
  drop constraint if exists study_sessions_user_id_fkey,
  add constraint study_sessions_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

alter table if exists public.daily_reflections
  drop constraint if exists daily_reflections_user_id_fkey,
  add constraint daily_reflections_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

alter table if exists public.weekly_reviews
  drop constraint if exists weekly_reviews_user_id_fkey,
  add constraint weekly_reviews_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

alter table if exists public.monthly_reviews
  drop constraint if exists monthly_reviews_user_id_fkey,
  add constraint monthly_reviews_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

-- 6) Add user-scoped uniqueness
create unique index if not exists daily_reflections_user_date_uidx
  on public.daily_reflections (user_id, date);

create unique index if not exists weekly_reviews_user_week_uidx
  on public.weekly_reviews (user_id, week_start_date);

create unique index if not exists monthly_reviews_user_month_uidx
  on public.monthly_reviews (user_id, month);

create unique index if not exists habit_logs_user_habit_date_uidx
  on public.habit_logs (user_id, habit_id, date);

-- 7) Helpful query indexes
create index if not exists tasks_user_date_idx on public.tasks (user_id, date);
create index if not exists study_sessions_user_date_idx on public.study_sessions (user_id, date);
create index if not exists habits_user_idx on public.habits (user_id);

-- 8) Enable RLS
alter table public.tasks enable row level security;
alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;
alter table public.study_sessions enable row level security;
alter table public.daily_reflections enable row level security;
alter table public.weekly_reviews enable row level security;
alter table public.monthly_reviews enable row level security;

-- 9) Replace existing policies idempotently
drop policy if exists tasks_select_own on public.tasks;
drop policy if exists tasks_insert_own on public.tasks;
drop policy if exists tasks_update_own on public.tasks;
drop policy if exists tasks_delete_own on public.tasks;

create policy tasks_select_own on public.tasks
  for select using (auth.uid() = user_id);
create policy tasks_insert_own on public.tasks
  for insert with check (auth.uid() = user_id);
create policy tasks_update_own on public.tasks
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy tasks_delete_own on public.tasks
  for delete using (auth.uid() = user_id);

-- habits
drop policy if exists habits_select_own on public.habits;
drop policy if exists habits_insert_own on public.habits;
drop policy if exists habits_update_own on public.habits;
drop policy if exists habits_delete_own on public.habits;

create policy habits_select_own on public.habits
  for select using (auth.uid() = user_id);
create policy habits_insert_own on public.habits
  for insert with check (auth.uid() = user_id);
create policy habits_update_own on public.habits
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habits_delete_own on public.habits
  for delete using (auth.uid() = user_id);

-- habit_logs
drop policy if exists habit_logs_select_own on public.habit_logs;
drop policy if exists habit_logs_insert_own on public.habit_logs;
drop policy if exists habit_logs_update_own on public.habit_logs;
drop policy if exists habit_logs_delete_own on public.habit_logs;

create policy habit_logs_select_own on public.habit_logs
  for select using (auth.uid() = user_id);
create policy habit_logs_insert_own on public.habit_logs
  for insert with check (auth.uid() = user_id);
create policy habit_logs_update_own on public.habit_logs
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habit_logs_delete_own on public.habit_logs
  for delete using (auth.uid() = user_id);

-- study_sessions
drop policy if exists study_sessions_select_own on public.study_sessions;
drop policy if exists study_sessions_insert_own on public.study_sessions;
drop policy if exists study_sessions_update_own on public.study_sessions;
drop policy if exists study_sessions_delete_own on public.study_sessions;

create policy study_sessions_select_own on public.study_sessions
  for select using (auth.uid() = user_id);
create policy study_sessions_insert_own on public.study_sessions
  for insert with check (auth.uid() = user_id);
create policy study_sessions_update_own on public.study_sessions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy study_sessions_delete_own on public.study_sessions
  for delete using (auth.uid() = user_id);

-- daily_reflections
drop policy if exists daily_reflections_select_own on public.daily_reflections;
drop policy if exists daily_reflections_insert_own on public.daily_reflections;
drop policy if exists daily_reflections_update_own on public.daily_reflections;
drop policy if exists daily_reflections_delete_own on public.daily_reflections;

create policy daily_reflections_select_own on public.daily_reflections
  for select using (auth.uid() = user_id);
create policy daily_reflections_insert_own on public.daily_reflections
  for insert with check (auth.uid() = user_id);
create policy daily_reflections_update_own on public.daily_reflections
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy daily_reflections_delete_own on public.daily_reflections
  for delete using (auth.uid() = user_id);

-- weekly_reviews
drop policy if exists weekly_reviews_select_own on public.weekly_reviews;
drop policy if exists weekly_reviews_insert_own on public.weekly_reviews;
drop policy if exists weekly_reviews_update_own on public.weekly_reviews;
drop policy if exists weekly_reviews_delete_own on public.weekly_reviews;

create policy weekly_reviews_select_own on public.weekly_reviews
  for select using (auth.uid() = user_id);
create policy weekly_reviews_insert_own on public.weekly_reviews
  for insert with check (auth.uid() = user_id);
create policy weekly_reviews_update_own on public.weekly_reviews
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy weekly_reviews_delete_own on public.weekly_reviews
  for delete using (auth.uid() = user_id);

-- monthly_reviews
drop policy if exists monthly_reviews_select_own on public.monthly_reviews;
drop policy if exists monthly_reviews_insert_own on public.monthly_reviews;
drop policy if exists monthly_reviews_update_own on public.monthly_reviews;
drop policy if exists monthly_reviews_delete_own on public.monthly_reviews;

create policy monthly_reviews_select_own on public.monthly_reviews
  for select using (auth.uid() = user_id);
create policy monthly_reviews_insert_own on public.monthly_reviews
  for insert with check (auth.uid() = user_id);
create policy monthly_reviews_update_own on public.monthly_reviews
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy monthly_reviews_delete_own on public.monthly_reviews
  for delete using (auth.uid() = user_id);

-- 10) Required grants for app role
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
